"""
Configuration settings and column constants for Solar PV AI Pipeline
"""
from pathlib import Path

# Base Paths
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw" / "nise"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
MODELS_DIR = BASE_DIR / "models"
RESULTS_DIR = BASE_DIR / "results"
DOCS_DIR = BASE_DIR / "docs"

NISE_FILE_PATH = RAW_DATA_DIR / "Inverter Report.xlsx"
CLEANED_DATA_PATH = PROCESSED_DATA_DIR / "cleaned_data.csv"
MODEL_DATA_PATH = PROCESSED_DATA_DIR / "model_data.csv"

# Meteorological Feature
IRRADIANCE_COL = "RADIATION 500 KW"

# Main Plant & Subsystem Power Columns (Raw NISE Dataset)
POWER_COLUMNS_MAP = {
    "SURYA_BHAVAN_150KW": [
        "SMA-1 ACTIVE POWER", "SMA-2 ACTIVE POWER", "SMA-3 ACTIVE POWER",
        "SMA-4 ACTIVE POWER", "SMA-5 ACTIVE POWER", "SMA-6 ACTIVE POWER"
    ],
    "NEW_GUEST_HOUSE_25KW": ["DELTA-1 ACTIVE POWER "],
    "OLD_GUEST_HOUSE_7.5KW": [" ACTIVE POWER "],
    "ADITYA_BHAVAN_7.5KW": ["DELTA-1 ACTIVE POWER .1"],
    "BIFACIAL_MONOFACIAL_10KW": ["SUNGROW-1 ACTIVE POWER"],
    "BIFACIAL_TILTED_5KW": ["SOLIS-2 ACTIVE POWER "],
    "BIFACIAL_VERTICAL_5KW": ["SOLIS-3 ACTIVE POWER"],
    "IBC_100KW": ["DELTA-1  ACTIVE POWER", "DELTA-2   ACTIVE POWER"],
    "MULTI_CSI_75KW": ["DELTA-1 ACTIVE POWER .2", "DELTA-2 ACTIVE POWER"],
    "HIT_100KW": ["DELTA-3 ACTIVE POWER", "DELTA-4 ACTIVE POWER"],
    "CIGS_100KW": ["HELIOS-1 ACTIVE POWER "],
    "CDTE_100KW": ["HELIOS-2  ACTIVE POWER "]
}

# Tariff
DEFAULT_TARIFF_INR_KWH = 8.0
SAMPLING_INTERVAL_MINUTES = 10
SAMPLING_INTERVAL_HOURS = SAMPLING_INTERVAL_MINUTES / 60.0
